---
name: "ğŸš€ Deploy Wiki"

on:
  push:
    branches: [ main ]
    tags: ['v*.*.*']
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true
    steps:
      - name: â¤µï¸ Check out code from GitHub
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
        id: prepare_tag
        if: startsWith(github.ref, 'refs/tags/')
      - run: |
          TAG_NAME="${GITHUB_REF##refs/tags/}"
          echo "::set-output name=tag_name::${TAG_NAME}"
          echo "::set-output name=deploy_tag_name::deploy-${TAG_NAME}"
      - name: 'ğŸš€ Deploy'
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAT }}
#          deploy_key: ${{ secrets.DEPLOY_KEY }}
          external_repository: z-shell/z-a-meta-plugins
          publish_branch: gh-pages
          publish_dir: ./docs
#          cname: wiki.zshell.dev
          keep_files: true
          allow_empty_commit: true
          user_name: digital-teams[bot]
          user_email: digital-teams@pm.me
          full_commit_message: ${{ github.event.head_commit.message }}
          tag_name: ${{ steps.prepare_tag.outputs.deploy_tag_name }}
          tag_message: 'Deployment ${{ steps.prepare_tag.outputs.tag_name }}'
