---
name: "â­• Trunk"
on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request:
    types: [opened, synchronize]
  schedule:
    - cron: "0 06 * * 5"
    - cron: "0 06 * * 2"
  workflow_dispatch: {}

jobs:
  check:
    if: github.event.schedule != '0 06 * * 5'
    uses: z-shell/.github/.github/workflows/trunk.yml@main
  upload:
    if: github.event.schedule == '0 06 * * 5'
    uses: z-shell/.github/.github/workflows/trunk.yml@main
    secrets:
      trunk-token: ${{ secrets.TRUNK_TOKEN }}
  upgrade:
    if: github.event.schedule == '0 06 * * 2'
    uses: z-shell/.github/.github/workflows/trunk.yml@main
    with:
      action: upgrade
